// export const FORM_INPUT_BODY_INFORMATION = 'FORM_INPUT_BODY_INFORMATION';
export const LANDINGS_SCREEN_GENERATE_MOCK_DATA = 'LANDINGS_SCREEN_GENERATE_MOCK_DATA';

export const ADDWORK_POSTDATA_REQUEST = 'ADDWORK_POSTDATA_REQUEST';
export const ADDWORK_POSTDATA_RESPONSE = 'ADDWORK_POSTDATA_RESPONSE';

export const HOME_GET_BOOKINGLIST_REQUEST = 'HOME_GET_BOOKINGLIST_REQUEST';
export const HOME_GET_BOOKINGLIST_RESPONSE = 'HOME_GET_BOOKINGLIST_RESPONSE';

export const HOME_FINISHJOB_REQUEST = 'HOME_FINISHJOB_REQUEST';